"""corpus comun + flashcards

Revision ID: 881f70ac4f9d
Revises: 38c9d6c63716
Create Date: 2025-07-15 01:01:27.657917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881f70ac4f9d'
down_revision = '38c9d6c63716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence', schema=None) as batch_op:
       # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
      #  batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
